# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      dhcp4: no
      dhcp6: no
      addresses: [10.40.122.7/16]
      gateway4: 10.40.0.1
      nameservers:
              addresses: [10.48.0.99,8.8.8.8,8.8.4.4]
