network:
  version: 2
  renderer: networkd
  ethernets:
    # LAN LAG/802.3ad bundle: enp1s0
    enp1s0:
      dhcp4: no
    enp2s0:
      dhcp4: no
    # WAN LAG/802.3ad bundle
    enp3s0:
      dhcp4: no
      optional: true
    enp4s0:
      dhcp4: no
      optional: true
    enp5s0:
      dhcp4: no
      optional: true
    enp6s0:
      dhcp4: no
      optional: true
    # multi-homing: multi-ip, multi-gateway
    enp7s0:
      addresses: [10.0.0.10/24]
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
      - to: 0.0.0.0/0
        via: 10.0.0.1
        metric: 100
    enp8s0:
      addresses: [11.0.0.11/24]
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
      - to: 0.0.0.0/0
        via: 11.0.0.1
        metric: 100
  vlans:
    vlan.70:
      accept-ra: no
      id: 70
      link: enp7s0
    vlan.80:
      accept-ra: no
      id: 80
      link: enp8s0
  bonds:
    bond-lan1:
      interfaces: [enp1s0, enp2s0]
      addresses: [192.168.254.22/24]
      parameters:
        mode: 802.3ad
        mii-monitor-interval: 1
    bond-lan2:
      interfaces: [enp3s0, enp4s0]
      addresses: [172.10.46.101/24]
      gateway4: 172.10.0.1
      nameservers:
        search: [local]
        addresses: [8.8.8.8, 8.8.4.4]
      parameters:
        mode: active-backup
        mii-monitor-interval: 1
        gratuitious-arp: 5
  bridges:
    # Interface bridge
    br0:
      dhcp4: yes
      interfaces: [enp5s0, enp6s0]
    # VLAN bridge
    br1:
      addresses: [ 10.3.99.25/24 ]
      interfaces: [vlan.70, vlan.80]
