#!/bin/sh

# Uncomment the following two lines for regular desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xdefaults ] && xrdb $HOME/.Xdefaults

xsetroot -solid grey
vncconfig -iconic &

#xterm -geometry 100x20 -fa courier -fs 12 -ls -title "$VNCDESKTOP Desktop" -bg white &
konsole --notabbar --vt_sz 100x20 &

#export XKL_XMODMAP_DISABLE=1
# Window manager: #metacity #awesome #startkde #X11 #wmaker #startx #startxfce #/etc/X11/Xsession #startfluxbox
twm &
